"""add short description task

Revision ID: 7bc299dee6eb
Revises: 4283f5e50b25
Create Date: 2021-01-29 16:47:46.111265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc299dee6eb'
down_revision = '4283f5e50b25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('short_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'short_description')
    # ### end Alembic commands ###
